In [2]:
import pandas as pd

df=pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [5]:
df=df.sample(10000)

In [6]:
df.shape

(10000, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 22665 to 31343
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [8]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [9]:
df.head()

                                                  review  sentiment
22665  The British horror film was in terminal declin...          1
33339  (r#88) Brilliant, very entertaining show with ...          1
24963  The Incredible Melting Man plays like an exten...          0
9963   Now infamous Western that was (at its time) th...          0
39306  "The Crush" is a pleasant enough 40-something ...          0

In [10]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

"The Incredible Melting Man plays like an extended episode of The Six Million Dollar Man, but with violence and some nudity. I know this film is a bit crummy but I found it impossible not to kind of like it.The acting and script are not the best. But the effects are good for a 30 year old movie with a budget of $50 - the title character takes quite a while to actually melt but when he does it's reasonably impressive; we also have one inventive death scene involving electrocution. Of note too is the music, it's insane - a cheese-tastic medley of nonsense.Notable highlights: * Marvel at the slow-motion nurse who jumps through a pane of glass for absolutely no reason whatsoever.* Be amazed by a day in the life of a severed head.* Beware of the psychotic cannibalistic melting humanoid. Called Steve.* Be astonished when our hero takes a break from hunting the melting lunatic to have a bowl of soup and complain about insufficient crackers in the kitchen.This film is just too 70's for me to hate it. It's tacky and trashy but I thought it was a lot of fun. You could do a lot worse."

In [22]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [23]:
df['review']=df['review'].apply(clean_html)

In [24]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [25]:
df['review']=df['review'].apply(convert_lower)

In [26]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [27]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [17]:
df['review']=df['review'].apply(remove_special)

In [18]:
# Remove the stop words
import nltk

In [19]:
from nltk.corpus import stopwords

In [20]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [21]:
df

                                                  review  sentiment
22665  the british horror film was in terminal declin...          1
33339   r 88  brilliant  very entertaining show with ...          1
24963  the incredible melting man plays like an exten...          0
9963   now infamous western that was  at its time  th...          0
39306   the crush  is a pleasant enough 40 something ...          0
...                                                  ...        ...
49035  i ve been a fan of rachael s since the beginni...          1
13357  this is very much not the sort of movie for wh...          1
17692  out of all the parodies of star wars i ve seen...          1
22253  a wonderful story that should be seen by all f...          1
31343  ummm  please forgive me  but weren t more than...          0

[10000 rows x 2 columns]

In [28]:

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [29]:
df['review']=df['review'].apply(remove_stopwords)

In [30]:
df

                                                  review  sentiment
22665  [british, horror, film, terminal, decline, sta...          1
33339  [r, 88, brilliant, entertaining, show, spectac...          1
24963  [incredible, melting, man, plays, like, extend...          0
9963   [infamous, western, time, biggest, budgeted, d...          0
39306  [crush, pleasant, enough, 40, something, frien...          0
...                                                  ...        ...
49035  [fan, rachael, since, beginning, 30mm, food, n...          1
13357  [much, sort, movie, john, wayne, known, plays,...          1
17692  [parodies, star, wars, seen, probably, funnies...          1
22253  [wonderful, story, seen, families, story, acti...          1
31343  [ummm, please, forgive, half, characters, miss...          0

[10000 rows x 2 columns]

In [31]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [32]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [33]:
stem_words(['I','loved','loving','it'])

['I', 'love', 'love', 'it']

In [34]:
df['review']=df['review'].apply(stem_words)

In [35]:
df

                                                  review  sentiment
22665  [british, horror, film, termin, declin, start,...          1
33339  [r, 88, brilliant, entertain, show, spectacula...          1
24963  [incred, melt, man, play, like, extend, episod...          0
9963   [infam, western, time, biggest, budget, disast...          0
39306  [crush, pleasant, enough, 40, someth, friend, ...          0
...                                                  ...        ...
49035  [fan, rachael, sinc, begin, 30mm, food, networ...          1
13357  [much, sort, movi, john, wayn, known, play, di...          1
17692  [parodi, star, war, seen, probabl, funniest, p...          1
22253  [wonder, stori, seen, famili, stori, act, prod...          1
31343  [ummm, pleas, forgiv, half, charact, miss, ori...          0

[10000 rows x 2 columns]

In [36]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [37]:
df['review']=df['review'].apply(join_back)

In [38]:
df['review']

22665    british horror film termin declin start sevent...
33339    r 88 brilliant entertain show spectacular effe...
24963    incred melt man play like extend episod six mi...
9963     infam western time biggest budget disast holly...
39306    crush pleasant enough 40 someth friend romant ...
                               ...
49035    fan rachael sinc begin 30mm food network seen ...
13357    much sort movi john wayn known play diplomat m...
17692    parodi star war seen probabl funniest premis s...
22253    wonder stori seen famili stori act product val...
31343    ummm pleas forgiv half charact miss origin nov...
Name: review, Length: 10000, dtype: object

In [39]:
X=df.iloc[:,0:1].values

In [40]:
X.shape

(10000, 1)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [42]:
X=cv.fit_transform(df['review']).toarray()

In [43]:
X.shape

(10000, 2500)

In [44]:
X[0].mean()

0.0232

In [45]:
y=df.iloc[:,-1].values

In [46]:
y.shape

(10000,)

In [47]:
# X,y
# Training set
# Test Set(Already know the result)

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [49]:
X_train.shape

(8000, 2500)

In [50]:
X_test.shape

(2000, 2500)

In [51]:
y_train.shape

(8000,)

In [52]:
y_test.shape

(2000,)

In [53]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [54]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [55]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [56]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [57]:
y_test.shape

(2000,)

In [58]:
y_pred1.shape

(2000,)

In [59]:
from sklearn.metrics import accuracy_score

In [60]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.74
Multinomial 0.824
Bernaulli 0.8275